/**
 * Audience clamp algorithm (BI_DESIGN §3.2, verbatim 6 steps).
 *
 * Applied after the raw sheet list is generated by chart selection.
 * Each step is a pure function, independently unit-testable.
 *
 * Phase-1 additions (Slice 4):
 * - scatter / map_filled added to analyst allowedMarkTypes
 * - map_filled added to exec allowedMarkTypes (exec gets filled maps)
 * - kpi_tile sheets are exempt from per-sheet measure/dimension caps (STEP 5)
 * - stepEnsureKpiStrip: for exec, ensures the KPI band leads (STEP 3 variant)
 *
 * Phase E1 (Slice C — BI_DESIGN §9, Few/visionary layer) additions:
 * - `chartDeny` override: persona-denied mark types fall back to "bar" with a
 *   rationale note naming the `chartDeny` rule (new STEP, runs right after
 *   STEP 1 TRUNCATE and before the audience-level STEP 2 mark-type drop).
 * - `kpiEmphasis` override: caps the number of `kpi_tile` sheets in the KPI
 *   band (high=4 / medium=3 / low=2; new STEP, runs after STEP 3 KPI lead).
 */

import type { Audience, DashboardLayout, MarkType, SheetSpec } from "./schema.js";

// ---------------------------------------------------------------------------
// Master audience table (BI_DESIGN §3.1, Phase-1 updates)
// ---------------------------------------------------------------------------

export interface AudienceConstraints {
  maxSheets: number;
  minimumKpiCount: number;
  allowedMarkTypes: MarkType[];
  mapAllowed: boolean;
  /** Phase-1: whether map_filled (filled map) is allowed for this audience. */
  mapFilledAllowed: boolean;
  /** Phase-1: whether scatter is allowed for this audience. */
  scatterAllowed: boolean;
  defaultLayout: DashboardLayout;
  layoutOverrideAllowed: boolean;
  maxMeasuresPerSheet: number;
  maxDimensionsPerSheet: number;
  canvasWidth: number;
  canvasHeight: number;
}

export const AUDIENCE_CONSTRAINTS: Record<Audience, AudienceConstraints> = {
  exec: {
    maxSheets: 3,
    minimumKpiCount: 1,
    // Phase-1: exec gets map_filled but not bare scatter (exec wants clear narrative)
    allowedMarkTypes: ["bar", "line", "text", "map_filled"],
    mapAllowed: false,
    mapFilledAllowed: true,
    scatterAllowed: false,
    defaultLayout: "tiled_vertical",
    layoutOverrideAllowed: true,
    maxMeasuresPerSheet: 1,
    maxDimensionsPerSheet: 1,
    canvasWidth: 1000,
    canvasHeight: 800,
  },
  analyst: {
    maxSheets: 8,
    minimumKpiCount: 0,
    // Phase-1: analyst gets scatter and map_filled
    allowedMarkTypes: ["bar", "line", "text", "map", "scatter", "map_filled"],
    mapAllowed: true,
    mapFilledAllowed: true,
    scatterAllowed: true,
    defaultLayout: "tiled_horizontal",
    layoutOverrideAllowed: true,
    maxMeasuresPerSheet: 4,
    maxDimensionsPerSheet: 3,
    canvasWidth: 1200,
    canvasHeight: 900,
  },
  operational: {
    maxSheets: 6,
    minimumKpiCount: 1,
    allowedMarkTypes: ["text", "bar", "line"],
    mapAllowed: false,
    mapFilledAllowed: false,
    scatterAllowed: false,
    defaultLayout: "tiled_vertical",
    layoutOverrideAllowed: false,
    maxMeasuresPerSheet: 2,
    maxDimensionsPerSheet: 1,
    canvasWidth: 800,
    canvasHeight: 1200,
  },
  mixed: {
    maxSheets: 6,
    minimumKpiCount: 0,
    allowedMarkTypes: ["bar", "line", "text"],
    mapAllowed: false,
    mapFilledAllowed: false,
    scatterAllowed: false,
    defaultLayout: "tiled_vertical",
    layoutOverrideAllowed: true,
    maxMeasuresPerSheet: 2,
    maxDimensionsPerSheet: 2,
    canvasWidth: 1000,
    canvasHeight: 900,
  },
};

// ---------------------------------------------------------------------------
// Default fallback mark type per audience
// ---------------------------------------------------------------------------

function defaultMarkForAudience(audience: Audience, sheet: SheetSpec): MarkType {
  const hasDimension = sheet.cols.length > 0 || sheet.rows.length > 0;
  if (audience === "exec" || audience === "operational") {
    return hasDimension ? "bar" : "text";
  }
  // analyst / mixed
  return "bar";
}

// ---------------------------------------------------------------------------
// STEP 1 — TRUNCATE
//
// Phase-1: kpi_tile sheets do NOT count against the maxSheets budget because
// they form a single visual band (not individual chart panels). Only non-kpi_tile
// sheets are counted and truncated.
// ---------------------------------------------------------------------------

function stepTruncate(sheets: SheetSpec[], constraints: AudienceConstraints): SheetSpec[] {
  // Separate kpi_tile sheets (band) from chart sheets
  const kpiTileSheets = sheets.filter((s) => s.kind === "kpi_tile");
  const chartSheets = sheets.filter((s) => s.kind !== "kpi_tile");

  if (chartSheets.length <= constraints.maxSheets) {
    // If no truncation needed for chart sheets, just ensure kpi tiles fit their own cap
    return sheets;
  }

  // Truncate chart sheets to maxSheets
  const removed = chartSheets.length - constraints.maxSheets;
  const truncatedCharts = chartSheets.slice(0, constraints.maxSheets);
  const last = truncatedCharts[truncatedCharts.length - 1] as SheetSpec | undefined;
  if (!last) return [...kpiTileSheets, ...truncatedCharts];
  const updatedLast: SheetSpec = {
    ...last,
    rationale:
      (last.rationale ? last.rationale + " " : "") +
      `Truncated ${removed} chart sheet(s) to fit audience limit.`,
  };
  return [...kpiTileSheets, ...truncatedCharts.slice(0, -1), updatedLast];
}

// ---------------------------------------------------------------------------
// STEP 1.5 — APPLY PERSONA chartDeny (BI_DESIGN §9, Few/visionary layer)
//
// A persona can veto specific mark types via brand.yaml's `chartDeny` list
// (e.g. `["scatter", "map"]` for a client-facing dashboard). Denied marks
// fall back to "bar" — the same universal fallback used elsewhere in this
// module — with a rationale note naming the `chartDeny` rule so the agent
// can relay *why* a chart type changed. Matching is case-insensitive since
// brand.yaml is free-text YAML edited by non-engineers.
//
// This step is independent of (and runs before) STEP 2's audience-level
// `allowedMarkTypes` drop: STEP 2 enforces what the *audience* can perceive;
// this step enforces what the *persona* explicitly never wants to see.
// ---------------------------------------------------------------------------

function stepApplyChartDeny(
  sheets: SheetSpec[],
  chartDeny: readonly string[] | undefined,
): SheetSpec[] {
  if (!chartDeny || chartDeny.length === 0) return sheets;
  const denySet = new Set(chartDeny.map((m) => m.toLowerCase()));

  return sheets.map((sheet) => {
    if (!denySet.has(sheet.markType.toLowerCase())) return sheet;
    return {
      ...sheet,
      markType: "bar" as MarkType,
      geo: undefined,
      scatter: undefined,
      rationale:
        (sheet.rationale ? sheet.rationale + " " : "") +
        `Mark type "${sheet.markType}" is denied for this persona (chartDeny rule); replaced with bar.`,
    };
  });
}

// ---------------------------------------------------------------------------
// STEP 2 — DROP DISALLOWED MARK TYPES
// ---------------------------------------------------------------------------

function stepDropDisallowedMarkTypes(
  sheets: SheetSpec[],
  audience: Audience,
  constraints: AudienceConstraints,
): SheetSpec[] {
  return sheets.map((sheet) => {
    if (constraints.allowedMarkTypes.includes(sheet.markType)) return sheet;
    const replacement = defaultMarkForAudience(audience, sheet);
    return {
      ...sheet,
      markType: replacement,
      rationale:
        (sheet.rationale ? sheet.rationale + " " : "") +
        "Mark type replaced to comply with audience constraints.",
    };
  });
}

// ---------------------------------------------------------------------------
// STEP 3 — ENSURE KPI LEAD
// ---------------------------------------------------------------------------

function stepEnsureKpiLead(
  sheets: SheetSpec[],
  constraints: AudienceConstraints,
  firstMeasureName: string,
): SheetSpec[] {
  if (constraints.minimumKpiCount === 0) return sheets;
  // A kpi_tile or a text mark at index 0 satisfies the KPI lead requirement
  const firstSheet = sheets[0];
  if (firstSheet?.markType === "text") return sheets;

  const kpiSheet: SheetSpec = {
    title: "KPI",
    markType: "text",
    cols: [],
    rows: [],
    measures: firstMeasureName ? [firstMeasureName] : [],
    rationale: "Auto-inserted KPI lead sheet to satisfy audience minimum KPI requirement.",
  };

  // Phase-1: only count non-kpi_tile sheets against maxSheets for this step
  const chartSheets = sheets.filter((s) => s.kind !== "kpi_tile");
  const kpiTileSheets = sheets.filter((s) => s.kind === "kpi_tile");
  const withKpi = [kpiSheet, ...chartSheets];
  if (withKpi.length > constraints.maxSheets) {
    // Drop last chart sheet to make room (but keep kpi_tile band intact)
    return [...kpiTileSheets, ...withKpi.slice(0, constraints.maxSheets)];
  }
  return [...kpiTileSheets, ...withKpi];
}

// ---------------------------------------------------------------------------
// STEP 3.5 — CAP KPI TILES BY kpiEmphasis (BI_DESIGN §9, Few/visionary layer)
//
// A persona's `kpiEmphasis` (high | medium | low, from brand.yaml) caps how
// many kpi_tile sheets survive in the KPI band: high=4 (the existing default
// band size), medium=3, low=2. Extra tiles are dropped from the tail (lowest-
// priority measures — buildKpiStrip/rankMeasures already ordered the band by
// relevance) and a rationale note is appended to the last surviving tile.
// ---------------------------------------------------------------------------

/** Max KPI tiles per `kpiEmphasis` level (BI_DESIGN §9 FEW-2 / persona layer). */
export const KPI_EMPHASIS_MAX_TILES: Readonly<Record<"high" | "medium" | "low", number>> = {
  high: 4,
  medium: 3,
  low: 2,
};

/** Default KPI-tile cap when no `kpiEmphasis` override is supplied (matches the historical band size). */
export const DEFAULT_MAX_KPI_TILES = KPI_EMPHASIS_MAX_TILES.high;

function stepCapKpiTiles(sheets: SheetSpec[], maxKpiTiles: number): SheetSpec[] {
  const kpiTileSheets = sheets.filter((s) => s.kind === "kpi_tile");
  const otherSheets = sheets.filter((s) => s.kind !== "kpi_tile");

  if (kpiTileSheets.length <= maxKpiTiles) return sheets;

  const removed = kpiTileSheets.length - maxKpiTiles;
  const truncated = kpiTileSheets.slice(0, maxKpiTiles);
  const last = truncated[truncated.length - 1];
  if (!last) return [...truncated, ...otherSheets];

  const updatedLast: SheetSpec = {
    ...last,
    rationale:
      (last.rationale ? last.rationale + " " : "") +
      `Dropped ${removed} KPI tile(s) to respect this persona's kpiEmphasis setting.`,
  };
  return [...truncated.slice(0, -1), updatedLast, ...otherSheets];
}

// ---------------------------------------------------------------------------
// STEP 4 — ENFORCE LAYOUT
// ---------------------------------------------------------------------------

function stepEnforceLayout(
  audience: Audience,
  constraints: AudienceConstraints,
  requestedLayout?: DashboardLayout,
): DashboardLayout {
  if (audience === "operational") return "tiled_vertical";
  if (requestedLayout && constraints.layoutOverrideAllowed) return requestedLayout;
  // L-01: analyst with > 4 sheets → tiled_vertical (applied in plan.ts, not here)
  return constraints.defaultLayout;
}

// ---------------------------------------------------------------------------
// STEP 5 — CAP MEASURES AND DIMENSIONS PER SHEET
//
// Phase-1: kpi_tile sheets are EXEMPT from the per-sheet measure cap because
// they bind multiple measures (primary/comparison/delta) conceptually — the
// measures array only carries the primary measure, but the kpi block has more.
// ---------------------------------------------------------------------------

function stepCapPerSheet(sheets: SheetSpec[], constraints: AudienceConstraints): SheetSpec[] {
  return sheets.map((sheet) => {
    // Phase-1: kpi_tile sheets are exempt from caps
    if (sheet.kind === "kpi_tile") return sheet;

    const notes: string[] = [];
    let measures = sheet.measures;
    let cols = sheet.cols;
    let rows = sheet.rows;

    if (measures.length > constraints.maxMeasuresPerSheet) {
      measures = measures.slice(0, constraints.maxMeasuresPerSheet);
      notes.push(`Measures truncated to ${constraints.maxMeasuresPerSheet} (audience cap).`);
    }

    const totalDims = cols.length + rows.length;
    if (totalDims > constraints.maxDimensionsPerSheet) {
      // Keep cols first, then rows
      const combined = [...cols, ...rows].slice(0, constraints.maxDimensionsPerSheet);
      cols = combined.slice(0, cols.length).filter((_, i) => i < Math.min(cols.length, constraints.maxDimensionsPerSheet));
      rows = combined.slice(cols.length);
      notes.push(`Dimensions truncated to ${constraints.maxDimensionsPerSheet} (audience cap).`);
    }

    if (notes.length === 0) return sheet;
    return {
      ...sheet,
      measures,
      cols,
      rows,
      rationale: (sheet.rationale ? sheet.rationale + " " : "") + notes.join(" "),
    };
  });
}

// ---------------------------------------------------------------------------
// STEP 6 — MAP MARK GUARD
// ---------------------------------------------------------------------------

function stepMapMarkGuard(
  sheets: SheetSpec[],
  audience: Audience,
  constraints: AudienceConstraints,
): SheetSpec[] {
  return sheets.map((sheet) => {
    // Legacy "map" mark
    if (sheet.markType === "map" && !constraints.mapAllowed) {
      return {
        ...sheet,
        markType: "bar" as MarkType,
        rationale:
          (sheet.rationale ? sheet.rationale + " " : "") +
          "Map mark not allowed for this audience.",
      };
    }
    // Phase-1: "map_filled" mark — fall back to "bar" if not allowed
    if (sheet.markType === "map_filled" && !constraints.mapFilledAllowed) {
      return {
        ...sheet,
        markType: "bar" as MarkType,
        geo: undefined,
        rationale:
          (sheet.rationale ? sheet.rationale + " " : "") +
          "Filled map not allowed for this audience; replaced with bar.",
      };
    }
    // Phase-1: "scatter" mark — fall back to "bar" if not allowed
    if (sheet.markType === "scatter" && !constraints.scatterAllowed) {
      return {
        ...sheet,
        markType: "bar" as MarkType,
        scatter: undefined,
        rationale:
          (sheet.rationale ? sheet.rationale + " " : "") +
          "Scatter mark not allowed for this audience; replaced with bar.",
      };
    }
    return sheet;
  });
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

export interface ClampResult {
  sheets: SheetSpec[];
  dashboardLayout: DashboardLayout;
}

/**
 * Persona-driven overrides layered onto an audience's base constraints
 * (Phase E1, Slice A + Slice C). Every field is optional so an absent
 * override is a no-op.
 */
export interface AudienceConstraintOverrides {
  /** Override the audience's default max chart-sheet count. */
  maxSheets?: number;
  /**
   * BI_DESIGN §9 (Few/visionary layer): mark types this persona never wants
   * to see (from brand.yaml's `chartDeny`). Denied marks fall back to "bar"
   * with a rationale note (STEP 1.5). Matching is case-insensitive.
   */
  chartDeny?: string[];
  /**
   * BI_DESIGN §9: how prominent the KPI band should be (from brand.yaml's
   * `kpiEmphasis`). Caps the number of `kpi_tile` sheets: high=4 (default),
   * medium=3, low=2 (STEP 3.5).
   */
  kpiEmphasis?: "high" | "medium" | "low";
}

/**
 * Apply all audience clamp steps in order (BI_DESIGN §3.2, extended by §9).
 *
 * @param rawSheets           Sheet list from chart selection.
 * @param audience            Target audience.
 * @param firstMeasure        Name of the first available measure (for KPI insertion).
 * @param requestedLayout     Caller-supplied layout override (ignored for operational).
 * @param constraintOverrides Optional persona-driven overrides layered onto the
 *                            audience's base constraints (maxSheets, chartDeny, kpiEmphasis).
 */
export function applyAudienceClamps(
  rawSheets: SheetSpec[],
  audience: Audience,
  firstMeasure = "",
  requestedLayout?: DashboardLayout,
  constraintOverrides?: AudienceConstraintOverrides,
): ClampResult {
  const baseConstraints = AUDIENCE_CONSTRAINTS[audience];
  const constraints: AudienceConstraints =
    constraintOverrides?.maxSheets !== undefined
      ? { ...baseConstraints, maxSheets: constraintOverrides.maxSheets }
      : baseConstraints;
  const maxKpiTiles = constraintOverrides?.kpiEmphasis
    ? KPI_EMPHASIS_MAX_TILES[constraintOverrides.kpiEmphasis]
    : DEFAULT_MAX_KPI_TILES;

  let sheets = stepTruncate(rawSheets, constraints);
  sheets = stepApplyChartDeny(sheets, constraintOverrides?.chartDeny);
  sheets = stepDropDisallowedMarkTypes(sheets, audience, constraints);
  sheets = stepEnsureKpiLead(sheets, constraints, firstMeasure);
  sheets = stepCapKpiTiles(sheets, maxKpiTiles);
  const dashboardLayout = stepEnforceLayout(audience, constraints, requestedLayout);
  sheets = stepCapPerSheet(sheets, constraints);
  sheets = stepMapMarkGuard(sheets, audience, constraints);

  return { sheets, dashboardLayout };
}
