/**
 * Audience clamp algorithm (BI_DESIGN §3.2, verbatim 6 steps).
 *
 * Applied after the raw sheet list is generated by chart selection.
 * Each step is a pure function, independently unit-testable.
 */

import type { Audience, DashboardLayout, MarkType, SheetSpec } from "./schema.js";

// ---------------------------------------------------------------------------
// Master audience table (BI_DESIGN §3.1)
// ---------------------------------------------------------------------------

export interface AudienceConstraints {
  maxSheets: number;
  minimumKpiCount: number;
  allowedMarkTypes: MarkType[];
  mapAllowed: boolean;
  defaultLayout: DashboardLayout;
  layoutOverrideAllowed: boolean;
  maxMeasuresPerSheet: number;
  maxDimensionsPerSheet: number;
  canvasWidth: number;
  canvasHeight: number;
}

export const AUDIENCE_CONSTRAINTS: Record<Audience, AudienceConstraints> = {
  exec: {
    maxSheets: 3,
    minimumKpiCount: 1,
    allowedMarkTypes: ["bar", "line", "text"],
    mapAllowed: false,
    defaultLayout: "tiled_vertical",
    layoutOverrideAllowed: true,
    maxMeasuresPerSheet: 1,
    maxDimensionsPerSheet: 1,
    canvasWidth: 1000,
    canvasHeight: 800,
  },
  analyst: {
    maxSheets: 8,
    minimumKpiCount: 0,
    allowedMarkTypes: ["bar", "line", "text", "map"],
    mapAllowed: true,
    defaultLayout: "tiled_horizontal",
    layoutOverrideAllowed: true,
    maxMeasuresPerSheet: 4,
    maxDimensionsPerSheet: 3,
    canvasWidth: 1200,
    canvasHeight: 900,
  },
  operational: {
    maxSheets: 6,
    minimumKpiCount: 1,
    allowedMarkTypes: ["text", "bar", "line"],
    mapAllowed: false,
    defaultLayout: "tiled_vertical",
    layoutOverrideAllowed: false,
    maxMeasuresPerSheet: 2,
    maxDimensionsPerSheet: 1,
    canvasWidth: 800,
    canvasHeight: 1200,
  },
  mixed: {
    maxSheets: 6,
    minimumKpiCount: 0,
    allowedMarkTypes: ["bar", "line", "text"],
    mapAllowed: false,
    defaultLayout: "tiled_vertical",
    layoutOverrideAllowed: true,
    maxMeasuresPerSheet: 2,
    maxDimensionsPerSheet: 2,
    canvasWidth: 1000,
    canvasHeight: 900,
  },
};

// ---------------------------------------------------------------------------
// Default fallback mark type per audience
// ---------------------------------------------------------------------------

function defaultMarkForAudience(audience: Audience, sheet: SheetSpec): MarkType {
  const hasDimension = sheet.cols.length > 0 || sheet.rows.length > 0;
  if (audience === "exec" || audience === "operational") {
    return hasDimension ? "bar" : "text";
  }
  // analyst / mixed
  return "bar";
}

// ---------------------------------------------------------------------------
// STEP 1 — TRUNCATE
// ---------------------------------------------------------------------------

function stepTruncate(sheets: SheetSpec[], constraints: AudienceConstraints): SheetSpec[] {
  if (sheets.length <= constraints.maxSheets) return sheets;
  const removed = sheets.length - constraints.maxSheets;
  const truncated = sheets.slice(0, constraints.maxSheets);
  // Attach rationale to the last kept sheet
  const last = truncated[truncated.length - 1] as SheetSpec | undefined;
  if (!last) return truncated;
  const updatedLast: SheetSpec = {
    ...last,
    rationale:
      (last.rationale ? last.rationale + " " : "") +
      `Truncated ${removed} sheet(s) to fit audience limit.`,
  };
  return [...truncated.slice(0, -1), updatedLast];
}

// ---------------------------------------------------------------------------
// STEP 2 — DROP DISALLOWED MARK TYPES
// ---------------------------------------------------------------------------

function stepDropDisallowedMarkTypes(
  sheets: SheetSpec[],
  audience: Audience,
  constraints: AudienceConstraints,
): SheetSpec[] {
  return sheets.map((sheet) => {
    if (constraints.allowedMarkTypes.includes(sheet.markType)) return sheet;
    const replacement = defaultMarkForAudience(audience, sheet);
    return {
      ...sheet,
      markType: replacement,
      rationale:
        (sheet.rationale ? sheet.rationale + " " : "") +
        "Mark type replaced to comply with audience constraints.",
    };
  });
}

// ---------------------------------------------------------------------------
// STEP 3 — ENSURE KPI LEAD
// ---------------------------------------------------------------------------

function stepEnsureKpiLead(
  sheets: SheetSpec[],
  constraints: AudienceConstraints,
  firstMeasureName: string,
): SheetSpec[] {
  if (constraints.minimumKpiCount === 0) return sheets;
  if (sheets[0]?.markType === "text") return sheets;

  const kpiSheet: SheetSpec = {
    title: "KPI",
    markType: "text",
    cols: [],
    rows: [],
    measures: firstMeasureName ? [firstMeasureName] : [],
    rationale: "Auto-inserted KPI lead sheet to satisfy audience minimum KPI requirement.",
  };

  const withKpi = [kpiSheet, ...sheets];
  if (withKpi.length > constraints.maxSheets) {
    // Drop last to make room
    return withKpi.slice(0, constraints.maxSheets);
  }
  return withKpi;
}

// ---------------------------------------------------------------------------
// STEP 4 — ENFORCE LAYOUT
// ---------------------------------------------------------------------------

function stepEnforceLayout(
  audience: Audience,
  constraints: AudienceConstraints,
  requestedLayout?: DashboardLayout,
): DashboardLayout {
  if (audience === "operational") return "tiled_vertical";
  if (requestedLayout && constraints.layoutOverrideAllowed) return requestedLayout;
  // L-01: analyst with > 4 sheets → tiled_vertical (applied in plan.ts, not here)
  return constraints.defaultLayout;
}

// ---------------------------------------------------------------------------
// STEP 5 — CAP MEASURES AND DIMENSIONS PER SHEET
// ---------------------------------------------------------------------------

function stepCapPerSheet(sheets: SheetSpec[], constraints: AudienceConstraints): SheetSpec[] {
  return sheets.map((sheet) => {
    const notes: string[] = [];
    let measures = sheet.measures;
    let cols = sheet.cols;
    let rows = sheet.rows;

    if (measures.length > constraints.maxMeasuresPerSheet) {
      measures = measures.slice(0, constraints.maxMeasuresPerSheet);
      notes.push(`Measures truncated to ${constraints.maxMeasuresPerSheet} (audience cap).`);
    }

    const totalDims = cols.length + rows.length;
    if (totalDims > constraints.maxDimensionsPerSheet) {
      // Keep cols first, then rows
      const combined = [...cols, ...rows].slice(0, constraints.maxDimensionsPerSheet);
      cols = combined.slice(0, cols.length).filter((_, i) => i < Math.min(cols.length, constraints.maxDimensionsPerSheet));
      rows = combined.slice(cols.length);
      notes.push(`Dimensions truncated to ${constraints.maxDimensionsPerSheet} (audience cap).`);
    }

    if (notes.length === 0) return sheet;
    return {
      ...sheet,
      measures,
      cols,
      rows,
      rationale: (sheet.rationale ? sheet.rationale + " " : "") + notes.join(" "),
    };
  });
}

// ---------------------------------------------------------------------------
// STEP 6 — MAP MARK GUARD
// ---------------------------------------------------------------------------

function stepMapMarkGuard(
  sheets: SheetSpec[],
  audience: Audience,
  constraints: AudienceConstraints,
): SheetSpec[] {
  if (constraints.mapAllowed) return sheets;
  return sheets.map((sheet) => {
    if (sheet.markType !== "map") return sheet;
    return {
      ...sheet,
      markType: "bar" as MarkType,
      rationale:
        (sheet.rationale ? sheet.rationale + " " : "") +
        "Map mark not allowed for this audience.",
    };
  });
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

export interface ClampResult {
  sheets: SheetSpec[];
  dashboardLayout: DashboardLayout;
}

/**
 * Apply all 6 audience clamp steps in order (BI_DESIGN §3.2).
 *
 * @param rawSheets        Sheet list from chart selection.
 * @param audience         Target audience.
 * @param firstMeasure     Name of the first available measure (for KPI insertion).
 * @param requestedLayout  Caller-supplied layout override (ignored for operational).
 */
export function applyAudienceClamps(
  rawSheets: SheetSpec[],
  audience: Audience,
  firstMeasure = "",
  requestedLayout?: DashboardLayout,
): ClampResult {
  const constraints = AUDIENCE_CONSTRAINTS[audience];

  let sheets = stepTruncate(rawSheets, constraints);
  sheets = stepDropDisallowedMarkTypes(sheets, audience, constraints);
  sheets = stepEnsureKpiLead(sheets, constraints, firstMeasure);
  const dashboardLayout = stepEnforceLayout(audience, constraints, requestedLayout);
  sheets = stepCapPerSheet(sheets, constraints);
  sheets = stepMapMarkGuard(sheets, audience, constraints);

  return { sheets, dashboardLayout };
}
