#!/usr/bin/env -S npx tsx
/**
 * generate-cron.ts — Emits a crontab line + macOS launchd plist template that
 * invoke `refresh-local.ts` on a schedule (Phase E2 slice C).
 *
 * Tableau Cloud cannot itself schedule a refresh for a local-file-based
 * datasource (no Bridge) — see `refresh-local.ts` and the Phase E2 plan's
 * design-around #1. This script only GENERATES the schedule artifacts; it
 * never installs them (no `crontab -e`, no `launchctl load` is ever run
 * here) so the operator reviews and installs deliberately.
 *
 * Usage:
 *   npx tsx scripts/generate-cron.ts --daily 03:30 --file <path> --name <ds name> --project <project> [--persona <name>] [--write]
 *   npx tsx scripts/generate-cron.ts --hourly --file <path> --name <ds name> --project <project> [--write]
 *   npm run cron:generate -- --daily 03:30 --file ... --name ... --project ...
 *
 * `--write` additionally saves both artifacts under scripts/cron/
 * (gitignored — contains local file paths, not committed) instead of only
 * printing to stdout.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import {
  buildCrontabLine,
  buildLaunchdPlist,
  isValidDailyTime,
  launchdLabel,
  slugify,
  type CronArtifactInput,
  type CronSchedule,
} from "./cronTemplates.js";

const MODULE_DIR = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(MODULE_DIR, "..");

export interface GenerateCronArgs {
  schedule: CronSchedule;
  file: string;
  name: string;
  project: string;
  persona?: string;
  write: boolean;
}

/** Parses `(--daily HH:MM | --hourly) --file <path> --name <name> --project <project> [--persona <name>] [--write]`. */
export function parseArgs(argv: string[]): GenerateCronArgs {
  const rest = argv.slice(2);
  const values: Record<string, string> = {};
  let write = false;
  let dailyTime: string | undefined;
  let hourly = false;

  for (let i = 0; i < rest.length; i++) {
    const arg = rest[i] ?? "";
    if (arg === "--write") {
      write = true;
      continue;
    }
    if (arg === "--hourly") {
      hourly = true;
      continue;
    }
    if (arg === "--daily") {
      dailyTime = rest[i + 1];
      i += 1;
      continue;
    }
    if (arg.startsWith("--")) {
      const key = arg.slice(2);
      const next = rest[i + 1];
      if (next === undefined || next.startsWith("--")) {
        throw new Error(`Missing value for --${key}.`);
      }
      values[key] = next;
      i += 1;
    }
  }

  if (hourly === (dailyTime !== undefined)) {
    throw new Error("Specify exactly one of --daily HH:MM or --hourly.");
  }
  if (dailyTime !== undefined && !isValidDailyTime(dailyTime)) {
    throw new Error(`--daily expects 24-hour "HH:MM" (got "${dailyTime}").`);
  }

  const required = ["file", "name", "project"] as const;
  const missing = required.filter((k) => !values[k]);
  if (missing.length > 0) {
    throw new Error(
      `Missing required argument(s): ${missing.map((m) => `--${m}`).join(", ")}. ` +
        "Usage: generate-cron.ts (--daily HH:MM | --hourly) --file <path> --name <ds name> " +
        "--project <project> [--persona <name>] [--write]",
    );
  }

  const schedule: CronSchedule = hourly ? { kind: "hourly" } : { kind: "daily", time: dailyTime as string };

  return {
    schedule,
    file: values["file"] as string,
    name: values["name"] as string,
    project: values["project"] as string,
    ...(values["persona"] !== undefined ? { persona: values["persona"] } : {}),
    write,
  };
}

/** Renders the full stdout block (install instructions + both artifacts). Pure — no I/O. */
export function renderOutput(args: GenerateCronArgs, repoRoot: string): { crontabLine: string; plist: string; label: string; text: string } {
  const input: CronArtifactInput = {
    schedule: args.schedule,
    invocation: {
      file: args.file,
      name: args.name,
      project: args.project,
      ...(args.persona !== undefined ? { persona: args.persona } : {}),
    },
    repoRoot,
  };
  const slug = slugify(args.name);
  const label = launchdLabel(slug);
  const crontabLine = buildCrontabLine(input);
  const plist = buildLaunchdPlist(input, label);
  const scheduleDescription =
    args.schedule.kind === "hourly" ? "hourly (minute 0)" : `daily at ${args.schedule.time}`;

  const text = `# refresh-local cron/launchd artifacts for datasource "${args.name}" (${scheduleDescription})
#
# Cloud cannot refresh a local-file datasource without Tableau Bridge — this
# job re-ingests "${args.file}" and re-publishes it (overwrite=true) on the
# schedule below. Generated by \`npm run cron:generate\`; NOTHING is installed
# automatically — review, then install ONE of the two mechanisms below.
#
# --- crontab ---------------------------------------------------------------
# Install:
#   (crontab -l 2>/dev/null; echo '${crontabLine}') | crontab -
# Verify:
#   crontab -l
# Uninstall:
#   crontab -e   # then delete the line below

${crontabLine}

# --- macOS launchd (recommended: survives reboot, catches up missed runs) --
# Install:
#   cp <this-plist-file> ~/Library/LaunchAgents/${label}.plist
#   launchctl load ~/Library/LaunchAgents/${label}.plist
# Verify:
#   launchctl list | grep ${label}
# Uninstall:
#   launchctl unload ~/Library/LaunchAgents/${label}.plist && rm ~/Library/LaunchAgents/${label}.plist

${plist}`;

  return { crontabLine, plist, label, text };
}

function main(): void {
  let args: GenerateCronArgs;
  try {
    args = parseArgs(process.argv);
  } catch (err) {
    console.error(err instanceof Error ? err.message : String(err));
    process.exit(1);
    return;
  }

  const { crontabLine, plist, label, text } = renderOutput(args, REPO_ROOT);
  console.log(text);

  if (args.write) {
    const slug = slugify(args.name);
    const dir = resolve(REPO_ROOT, "scripts", "cron");
    mkdirSync(dir, { recursive: true });
    const crontabPath = resolve(dir, `${slug}.crontab.txt`);
    const plistPath = resolve(dir, `${label}.plist`);
    writeFileSync(crontabPath, `${crontabLine}\n`, "utf8");
    writeFileSync(plistPath, plist, "utf8");
    console.log(`\nWrote:\n  ${crontabPath}\n  ${plistPath}`);
  }
}

// Only auto-run when executed directly (tsx/node), never when imported by tests.
const isEntrypoint =
  !!process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href;
if (isEntrypoint) {
  main();
}
